### ISSUE TITLE
Keyword tags

### ISSUE THREAD

**Issue by aenniw** [aenniw/jrobotremoteserver#14]
Add support for keyword taging via rpc get_keyword_tags

**Comment by aenniw** [comment]
2017-03-08 11:55:52,286 | ERROR | tp2003237864-495 | XmlRpcErrorLogger                | 525 - com.github.aenniw.jrobot-remote-server - 3.4.1 | No such handler: get_keyword_tags
org.apache.xmlrpc.server.XmlRpcNoSuchHandlerException: No such handler: get_keyword_tags
	at org.apache.xmlrpc.server.AbstractReflectiveHandlerMapping.getHandler(AbstractReflectiveHandlerMapping.java:214)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:45)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.doPost(RemoteServerServlet.java:137)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)[219:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.service(RemoteServerServlet.java:117)[525:com.github.aenniw.jrobot-remote-server:3.4.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)[219:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:427)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:984)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1045)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:236)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[224:org.eclipse.jetty.aggregate.jetty-all-server:8.1.19.v20160209]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_121]

**Comment by aenniw** [comment]
Introduced by [RobotFramework 3.0.2](https://github.com/robotframework/robotframework/blob/dc0581a46c5da6f632c7e505fafa22046a84ba3a/doc/releasenotes/rf-3.0.2.rst) namely [#2538](https://github.com/robotframework/robotframework/issues/2538)
